BASE_DIR = '../'
ACT_SET_PATH = BASE_DIR + 'data/acts'
SLOTS_SET_PATH = BASE_DIR + 'data/slots'
RESTAURANT_PATH = BASE_DIR +'data/restaurant_dict.json'
GOALS_PATH = BASE_DIR+'data/goals.json'
SL_US_MODEL_PATH = 'models/supervised_user_simulator_model.p'
SL_BINARIZERS_PATH = 'models/supervised_user_simulator_binarizers.p'
RLAGENT_MODEL = 'models/rlagent_model.p'
DSTC_PATH = BASE_DIR+'data/dstc2_traindev'
CONTENT_MANAGER_SAVE_PATH = BASE_DIR+'data/content_manger_cached.json'
NLG_PATTERNS_PATH = BASE_DIR+'data/nlg_patterns.json'
SL_AGENT_MODEL_PATH = BASE_DIR+'scripts/sl_agent.cat'
NLU_ACTON_MODEL_PATH = 'models/crf_acts_new.model'
NLU_SLOT_MODEL_PATH = 'models/crf_slots_new.model'
ONTOLOGY_PATH = BASE_DIR + 'data/ontology_new.json'

MAX_TURN = 30