BASE_DIR = '../'
ACT_SET_PATH = BASE_DIR + 'data/acts'
SLOTS_SET_PATH = BASE_DIR + 'data/slots'
RESTAURANT_PATH = BASE_DIR +'data/restaurant_dict.json'
GOALS_PATH = BASE_DIR+'data/goals.json'
SL_US_MODEL_PATH = 'models/supervised_user_simulator_model.p'
SL_BINARIZERS_PATH = 'models/supervised_user_simulator_binarizers.p'